export const GET_SKILL_CATEGORIES_REQUEST = "GET_SKILL_CATEGORIES_REQUEST";
export const GET_SKILL_CATEGORIES_SUCCESS = "GET_SKILL_CATEGORIES_SUCCESS";
export const GET_SKILL_CATEGORIES_FAILURE = "GET_SKILL_CATEGORIES_FAILURE";

export const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAILURE = "GET_SKILLS_FAILURE";

export const CREATE_SKILL_CATEGORY_REQUEST = "CREATE_SKILL_CATEGORY_REQUEST";
export const CREATE_SKILL_CATEGORY_SUCCESS = "CREATE_SKILL_CATEGORY_SUCCESS";
export const CREATE_SKILL_CATEGORY_FAILURE = "CREATE_SKILL_CATEGORY_FAILURE";

export const UPDATE_SKILL_CATEGORY_REQUEST = "UPDATE_SKILL_CATEGORY_REQUEST";
export const UPDATE_SKILL_CATEGORY_SUCCESS = "UPDATE_SKILL_CATEGORY_SUCCESS";
export const UPDATE_SKILL_CATEGORY_FAILURE = "UPDATE_SKILL_CATEGORY_FAILURE";

export const DELETE_SKILL_CATEGORY_SUCCESS = "DELETE_SKILL_CATEGORY_SUCCESS";
export const DELETE_SKILL_CATEGORY_FAILURE = "DELETE_SKILL_CATEGORY_FAILURE";

export const CREATE_SKILL_REQUEST = "CREATE_SKILL_REQUEST";
export const CREATE_SKILL_SUCCESS = "CREATE_SKILL_SUCCESS";
export const CREATE_SKILL_FAILURE = "CREATE_SKILL_FAILURE";

export const UPDATE_SKILL_REQUEST = "UPDATE_SKILL_REQUEST";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_FAILURE = "UPDATE_SKILL_FAILURE";

export const DELETE_SKILL_REQUEST = "DELETE_SKILL_REQUEST";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAILURE = "DELETE_SKILL_FAILURE";
