export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";

export const GET_MANAGERS_REQUEST = "GET_MANAGERS_REQUEST";
export const GET_MANAGERS_SUCCESS = "GET_MANAGERS_SUCCESS";
export const GET_MANAGERS_FAILURE = "GET_MANAGERS_FAILURE";

export const UPDATE_EMPLOYEE_ACCOUNT_REQUEST =
  "UPDATE_EMPLOYEE_ACCOUNT_REQUEST";
export const UPDATE_EMPLOYEE_ACCOUNT_SUCCESS =
  "UPDATE_EMPLOYEE_ACCOUNT_SUCCESS";
export const UPDATE_MANAGER_ACCOUNT_REQUEST = "UPDATE_MANAGER_ACCOUNT_REQUEST";
export const UPDATE_MANAGER_ACCOUNT_SUCCESS = "UPDATE_MANAGER_ACCOUNT_SUCCESS";
export const UPDATE_ACCOUNT_FAILURE = "UPDATE_ACCOUNT_FAILURE";
