export const GET_COURSE_PROGRAMS_REQUEST = "GET_COURSE_PROGRAMS_REQUEST";
export const GET_COURSE_PROGRAMS_SUCCESS = "GET_COURSE_PROGRAMS_SUCCESS";
export const GET_COURSE_PROGRAMS_FAILURE = "GET_COURSE_PROGRAMS_FAILURE";

export const CREATE_COURSE_PROGRAM_REQUEST = "CREATE_COURSE_PROGRAM_REQUEST";
export const CREATE_COURSE_PROGRAM_SUCCESS = "CREATE_COURSE_PROGRAM_SUCCESS";
export const CREATE_COURSE_PROGRAM_FAILURE = "CREATE_COURSE_PROGRAM_FAILURE";

export const UPDATE_COURSE_PROGRAM_REQUEST = "UPDATE_COURSE_PROGRAM_REQUEST";
export const UPDATE_COURSE_PROGRAM_SUCCESS = "UPDATE_COURSE_PROGRAM_SUCCESS";
export const UPDATE_COURSE_PROGRAM_FAILURE = "UPDATE_COURSE_PROGRAM_FAILURE";

export const DELETE_COURSE_PROGRAM_REQUEST = "DELETE_COURSE_PROGRAM_REQUEST";
export const DELETE_COURSE_PROGRAM_SUCCESS = "DELETE_COURSE_PROGRAM_SUCCESS";
export const DELETE_COURSE_PROGRAM_FAILURE = "DELETE_COURSE_PROGRAM_FAILURE";

export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";
